language: go

sudo: required

env: GOOGLE_APPLICATION_CREDENTIALS=/dev/shm/account.json

before_script:
- sudo apt update && sudo apt install -y unzip openssl secure-delete
- openssl aes-256-cbc -K $encrypted_fddb24ed60dc_key -iv $encrypted_fddb24ed60dc_iv
  -in infra/account.json.enc -out $GOOGLE_APPLICATION_CREDENTIALS -d

script:
- TF_ZIP=$(go run scripts/download-terraform.go)
- unzip $TF_ZIP -d /tmp
- cd infra
- "/tmp/terraform init"
- "/tmp/terraform apply -auto-approve -lock=true"

after_script:
- srm $GOOGLE_APPLICATION_CREDENTIALS
